skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrowq32026 = "GyqbbKLrvgjqo8k9M4RJ4Lvzqm279RdPyeUj7P6oM8Ln"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -- --nocapture"

[hooks]
